blog/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.blog_title, name="blog_title"),
    path('<int:article_id>', views.blog_article, name="blog_article"),
]

course/urls.py
from django.urls import path, include
# from django.views.generic import TemplateView
from .views import AboutView, CourseListView, ManageCourseListView, CreateCourseView, DeleteCourseView, CreateLessonView, ListLessonsView, DetailLessonView
from .views import StudentListLessonView

urlpatterns = [
    # path('about/', TemplateView.as_view(template_name="course/about.html")),
    path('about/', AboutView.as_view(), name="about"),    
    path('course-list/', CourseListView.as_view(), name="course_list"),
    path('manage-course/', ManageCourseListView.as_view(), name="manage_course"),
    path('create-course/', CreateCourseView.as_view(), name="create_course"),
    path('delete-course/<int:pk>/', DeleteCourseView.as_view(), name="delete_course"),
    path('create-lesson/', CreateLessonView.as_view(), name="create_lesson"),
    path('list-lessons/<int:course_id>/', ListLessonsView.as_view(), name="list_lessons"),
    path('detail-lesson/<int:lesson_id>/', DetailLessonView.as_view(), name="detail_lesson"),
    path('lessons-list/<int:course_id>/', StudentListLessonView.as_view(), name="lessons_list"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="home.html"), name="home"),
    path('blog/', include(("blog.urls", "blog"), namespace="blog")),
    path('account/', include(("account.urls", "account"), namespace='account')),
    path('pwd_reset/', include(("password_reset.urls", "pwd_reset"), namespace='pwd_reset')),
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('image/', include(('image.urls', 'image'), namespace='image')),
    path('course/', include(('course.urls', 'course'), namespace='course')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.contrib.auth.models import User
from slugify import slugify
from .fields import OrderField


class Course(models.Model):
    user = models.ForeignKey(User, related_name='courses_user', on_delete=models.CASCADE, verbose_name='用户')
    title = models.CharField(max_length=200, verbose_name='标题')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='SLUG')
    overview = models.TextField(verbose_name='概览')
    created = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    # 多对多不需要on_delete参数
    student = models.ManyToManyField(User, related_name="courses_joined", blank=True, verbose_name='学生')

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name
        ordering = ('-created',)

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(Course, self).save(*args, **kargs)

    def __str__(self):
        return self.title


# instance是Lesson的实例，filename是文件名
def user_directory_path(instance, filename):
    return "courses/user_{0}/{1}".format(instance.user.id, filename)


class Lesson(models.Model):
    user = models.ForeignKey(User, related_name='lesson_user', on_delete=models.CASCADE, verbose_name='用户')
    course = models.ForeignKey(Course, related_name='lesson', on_delete=models.CASCADE, verbose_name='课程')
    title = models.CharField(max_length=200, verbose_name='章节')
    video = models.FileField(upload_to=user_directory_path, verbose_name='视频地址')
    description = models.TextField(blank=True, verbose_name='章节描述')
    attach = models.FileField(blank=True, upload_to=user_directory_path, verbose_name='附件地址')
    created = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    order = OrderField(blank=True, for_fields=['course'])

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name
        ordering = ['order']

    def __str__(self):
        return '{}.{}'.format(self.order, self.title)

course/forms.py
from django import forms
from .models import Course, Lesson


class CreateCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ("title", "overview")


class CreateLessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['course', 'title', 'video', 'description', 'attach']

    # 只显示当前用户的课程
    def __init__(self, user, *args, **kwargs):
        super(CreateLessonForm, self).__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.filter(user=user)

course/views.py
from django.views.generic import TemplateView, ListView, DeleteView
from django.urls import reverse_lazy
# from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from django.shortcuts import redirect, render, get_object_or_404, render_to_response
from django.views import View
from django.views.generic.base import TemplateResponseMixin
from django.http import HttpResponse
from braces.views import LoginRequiredMixin
import json
from .forms import CreateCourseForm, CreateLessonForm
from .models import Course, Lesson


class AboutView(TemplateView):
    template_name = "course/about.html"


class CourseListView(ListView):
    # 指定模型、模板中的变量名、模板文件，实际上相当于courses=Course.objects.all()
    model = Course
    context_object_name = "courses"
    template_name = 'course/course_list.html'

    # def get_queryset(self):
    #     qs = super(CourseListView, self).get_queryset()
    #     return qs.filter(user=User.objects.filter(username=self.request.user))


# 带Mixin的都是用于后面的类，而不是作为视图使用
class UserMixin:
    # 当前用户的所有课程
    def get_queryset(self):
        qs = super(UserMixin, self).get_queryset()
        return qs.filter(user=self.request.user)


# 带Mixin的都是用于后面的类，而不是作为视图使用
class UserCourseMixin(UserMixin, LoginRequiredMixin):
    model = Course
    login_url = "/account/login/"


# 一般是先继承Mixin类(重写后的get_queryset，模型为Course，登陆后的用户才能访问，匿名用户引导到login_url)，再继承其他类
class ManageCourseListView(UserCourseMixin, ListView):
    context_object_name = "courses"
    template_name = 'course/manage/manage_course_list.html'


class CreateCourseView(UserCourseMixin, CreateView):
    fields = ['title', 'overview']
    template_name = 'course/manage/create_course.html'

    def post(self, request, *args, **kargs):
        form = CreateCourseForm(data=request.POST)
        if form.is_valid():
            new_course = form.save(commit=False)
            new_course.user = self.request.user
            new_course.save()
            return redirect("course:manage_course")
        return self.render_to_response({"form": form})


class DeleteCourseView(UserCourseMixin, DeleteView):
    template_name = 'course/manage/delete_course_confirm.html'
    success_url = reverse_lazy("course:manage_course")

    def dispatch(self, *args, **kwargs):
        resp = super(DeleteCourseView, self).dispatch(*args, **kwargs)
        if self.request.is_ajax():
            response_data = {"result": "ok"}
            return HttpResponse(json.dumps(response_data), content_type="application/json")
        else:
            return resp


class CreateLessonView(LoginRequiredMixin, View):
    model = Lesson
    login_url = "/account/login/"

    def get(self, request, *args, **kwargs):
        form = CreateLessonForm(user=self.request.user)
        return render(request, "course/manage/create_lesson.html", {"form": form})

    def post(self, request, *args, **kwargs):
        # 表单有文件上传，所以使用request.FILES
        form = CreateLessonForm(self.request.user, request.POST, request.FILES)
        if form.is_valid():
            new_lesson = form.save(commit=False)
            new_lesson.user = self.request.user
            new_lesson.save()
            return redirect("course:manage_course")


# TemplateResponseMixin提供支持模板的功能
class ListLessonsView(LoginRequiredMixin, TemplateResponseMixin, View):
    login_url = "/account/login/"
    template_name = 'course/manage/list_lessons.html'

    def get(self, request, course_id):
        course = get_object_or_404(Course, id=course_id)
        return self.render_to_response({'course': course})


class DetailLessonView(LoginRequiredMixin, TemplateResponseMixin, View):
    login_url = "/account/login/"
    template_name = "course/manage/detail_lesson.html"

    def get(self, request, lesson_id):
        lesson = get_object_or_404(Lesson, id=lesson_id)
        return self.render_to_response({"lesson": lesson})


# 继承自ListLessonsView可以获得登陆限制、支持模板、继承get方法(Course对象)
class StudentListLessonView(ListLessonsView):
    template_name = "course/studentlist_lessons.html"

    def post(self, request, *args, **kwargs):
        course = Course.objects.get(id=kwargs['course_id'])
        course.student.add(self.request.user)
        return HttpResponse("ok")

templates/course/about.html
{% extends "base.html" %}
{% block title %}关于我们{% endblock %}
{% block content %}
<div class="container">
  <h1 class="text-center">欢迎访问</h1>
    <p class="text-center">这里是学习Django开发的网站</p>
</div>
{% endblock %}

templates/course/course_list.html
{% extends "base.html" %}
{% block title %}课程列表{% endblock %}
{% block content %}
<div class="container">
  <table class="table table-hover">
    <tr>
      <td>序号</td>
      <td>课程标题</td>
      <td>讲师</td>
      <td>发布日期</td>
    </tr>
    {% for course in courses %}
    <tr id={{ forloop.counter }}>
      <td>{{ forloop.counter }}</td>
      <td><a href="{% url 'course:lessons_list' course.id %}">{{ course.title }}</a></td>
      <td>{{ course.user.username }}</td>
      <td>{{ course.created }}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

templates/course/studentlist_lessons.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}我的章节列表{% endblock %}
{% block content %}
<div class="container">
  <div class='text-center'>
    <h1>{{ course.title }}</h1>
    <p>章节列表</p>
    <form action="." method="post" class="form-horizontal">{% csrf_token %}
      <input type="button" onclick="start_learn({{course.id}})" value="开始学习">
    </form>

  </div>
  <table class="table table-hover" style="margin-top:10px">
    <tr>
      <td>序号</td>
      <td>内容标题</td>
      <td>概要</td>
      <td>发布日期</td>
    </tr>
    {% for lesson in course.lesson.all %}
    <tr id={{ forloop.counter }}>
      <td>{{ forloop.counter }}</td>
      <td><a href="{% url 'course:detail_lesson' lesson.id %}">{{ lesson.title }}</a></td>
      <td>{{ lesson.description | slice:'70'|linebreaks }}</td>
      <td>{{ lesson.created|date:"Y-m-d" }}</td>
    </tr>
    {% empty %}
    <p>还没有发布具体内容，请等待。</p>
    {% endfor %}
  </table>
</div>

<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "js/csrf.js" %}'></script>
<script>
    function start_learn(course_id){
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
               function getCookie(name) {
                   var cookieValue = null;
                   if (document.cookie && document.cookie != '') {
                       var cookies = document.cookie.split(';');
                       for (var i = 0; i < cookies.length; i++) {
                           var cookie = jQuery.trim(cookies[i]);
                           if (cookie.substring(0, name.length + 1) == (name + '=')) {
                               cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                               break;
                           }
                       }
                   }
                   return cookieValue;
               }
               if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                   xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
               }
            }
      });
      $.ajax({
        type: "POST",
        url: "{% url 'course:lessons_list' course.id %}",
        data: {'course_id':course_id},
        success:function(e){
          if(e=="ok"){
            alert("你已经报名该课程")
          }else{
             alert("出现一些错误")
          }
        },
      });
    }
</script>

{% endblock %}